# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of node
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.17.0
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Start FE
      run: npm start &
    - name: Wait for server to be ready
      run: npx wait-on http://localhost:3000
    - name: Install browsers
      run: npx playwright install --with-deps
    - name: Run UI tests
      run: npm playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
