# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of node
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Generate config file
      run: node generate-config.mjs
      env:
        API_URL: http://localhost:3030  
    - name: Start FE server
      run: npm start &
    - name: Start API server
      run: npm run server &
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  deploy_be:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
        service_id: ${{ secrets.RENDER_FE_DEPLOY_HOOK_KEY }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
  deploy_fe:
    runs-on: ubuntu-latest
    needs: deploy_be
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
        service_id: ${{ secrets.RENDER_BE_DEPLOY_HOOK_KEY }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true      

        